### ISSUE TITLE
4. Assemble 

### ISSUE THREAD

**Issue by HeathenToaster** [CENTURI-Hackathon-2022/syringe-driver#5]
# Assemble
Build the syringe driver

- [x] Replace the single stepper motor plugged on the CNC shield with the syringe driver

# Difficulties
- Make everything fit together

**Comment by jlopezalo** [comment]
![20220626_093846](https://user-images.githubusercontent.com/62241930/175804473-2dd07d31-a5c3-45de-96b4-c4df0eda5ba4.jpg)
d
