### ISSUE TITLE
5. Fill/Empty the syringe

### ISSUE THREAD

**Issue by HeathenToaster** [CENTURI-Hackathon-2022/syringe-driver#6]
# Fill/Empty the syringe
Use the previous steps to fill/empty the syringe

- [x] Make sure the travel distance is correct on grbl configuration
- [x] Make sure it goes home and empty the syringe ($H)
- [ ] Empty the air pumped 

# Difficulties
- Find when to stop the motor

**Comment by jlopezalo** [comment]
Completed. Implemented the following methods on the [SyringeDriver](https://github.com/CENTURI-Hackathon-2022/syringe-driver/blob/main/src/control_syringe.py) class:

- set_soft_limit_mm
- move_to_home
- empty_syringe
- fill_syringe
- purge_air
