### ISSUE TITLE
6. Deliver calibrated drops

### ISSUE THREAD

**Issue by HeathenToaster** [CENTURI-Hackathon-2022/syringe-driver#7]
# Deliver calibrated drops
Use the syringe driver to deliver drops of liquid

# Difficulties
- Compute the number of steps the motor has to move to yield the target volume

**Comment by jlopezalo** [comment]
Completed. Calibrated 10mL syringe and added the calibration factor (mm/mL) as property in the [SyringeDriver](https://github.com/CENTURI-Hackathon-2022/syringe-driver/blob/main/src/control_syringe.py) class: 
SyringeDriver.cal_factor

Added methods to convert volume to distance travelled and deliver volume:
- ml_to_mm --> Concerts mL to mm to travel
- jogg_x --> Jogg on the x axis at a set rate in %
- deliver_volume --> Deliver a certain volume in mL
